/**
 * CSV Parser Utility for TCG Card Tracker
 * Parses CSV files generated by PaperStream Capture or standard TCG exports.
 */

export function parseCSV(csvText) {
  if (!csvText || typeof csvText !== 'string') {
    return { headers: [], rows: [], data: [] };
  }

  // Normalize line endings
  const cleanText = csvText.replace(/\r\n/g, '\n').replace(/\r/g, '\n');
  const lines = cleanText.split('\n').filter(line => line.trim() !== '');

  if (lines.length === 0) {
    return { headers: [], rows: [], data: [] };
  }

  // Auto-detect delimiter (, or ; or \t)
  const firstLine = lines[0];
  let delimiter = ',';
  if ((firstLine.match(/;/g) || []).length > (firstLine.match(/,/g) || []).length) {
    delimiter = ';';
  } else if ((firstLine.match(/\t/g) || []).length > (firstLine.match(/,/g) || []).length) {
    delimiter = '\t';
  }

  function parseLine(line) {
    const result = [];
    let current = '';
    let inQuotes = false;

    for (let i = 0; i < line.length; i++) {
      const char = line[i];
      const nextChar = line[i + 1];

      if (char === '"') {
        if (inQuotes && nextChar === '"') {
          current += '"';
          i++; // Skip escaped quote
        } else {
          inQuotes = !inQuotes;
        }
      } else if (char === delimiter && !inQuotes) {
        result.push(current.trim());
        current = '';
      } else {
        current += char;
      }
    }
    result.push(current.trim());
    return result;
  }

  const rawHeaders = parseLine(lines[0]);
  const headers = rawHeaders.map(h => h.toLowerCase().replace(/^["']|["']$/g, ''));

  const rows = [];
  const data = [];

  for (let i = 1; i < lines.length; i++) {
    const values = parseLine(lines[i]);
    if (values.length === 0 || (values.length === 1 && values[0] === '')) continue;

    rows.push(values);

    const rowObj = {};
    headers.forEach((header, index) => {
      rowObj[header] = values[index] !== undefined ? values[index] : '';
    });
    data.push(rowObj);
  }

  return { headers: rawHeaders, rows, data, delimiter };
}

export function normalizeLanguage(langStr) {
  if (!langStr || typeof langStr !== 'string') return 'EN';
  const clean = langStr.trim().toUpperCase();
  if (clean === 'ENGLISH' || clean === 'EN' || clean === 'ENGLISCH') return 'EN';
  if (clean === 'GERMAN' || clean === 'DE' || clean === 'DEUTSCH') return 'DE';
  if (clean === 'FRENCH' || clean === 'FR' || clean === 'FRANZÖSISCH') return 'FR';
  if (clean === 'SPANISH' || clean === 'ES' || clean === 'SPANISCH') return 'ES';
  if (clean === 'ITALIAN' || clean === 'IT' || clean === 'ITALIENISCH') return 'IT';
  if (clean === 'JAPANESE' || clean === 'JP' || clean === 'JAPANISCH') return 'JP';
  if (clean === 'CHINESE' || clean === 'ZH' || clean === 'CHINESISCH') return 'ZH';
  if (clean === 'KOREAN' || clean === 'KO' || clean === 'KOREANISCH') return 'KO';
  if (clean === 'RUSSIAN' || clean === 'RU' || clean === 'RUSSISCH') return 'RU';
  return 'EN';
}

export function normalizeCondition(condStr) {
  if (!condStr || typeof condStr !== 'string') return 'NM';
  const clean = condStr.trim().toUpperCase();
  if (clean.includes('MINT') || clean === 'MT') return 'MT';
  if (clean.includes('NEAR') || clean === 'NM') return 'NM';
  if (clean.includes('EXCELLENT') || clean === 'EX') return 'EX';
  if (clean.includes('GOOD') || clean === 'GD') return 'GD';
  if (clean.includes('LIGHT') || clean === 'LP') return 'LP';
  if (clean.includes('PLAYED') || clean === 'PL') return 'PL';
  if (clean.includes('POOR') || clean === 'PO') return 'PO';
  return 'NM';
}

/**
 * Normalizes CSV records into standardized TCG Scan Items
 */
export function normalizeScanData(parsedCSV) {
  const { data } = parsedCSV;

  return data.map((row, index) => {
    // Attempt to map common column names
    const rawCode = row['card number'] || row['card_number'] || row['code'] || row['cardcode'] || row['number'] || row['id'] || row['zone ocr'] || row['ocr'] || '';
    const rawName = row['card name'] || row['card_name'] || row['name'] || row['title'] || '';
    const rawSet = row['set'] || row['expansion'] || row['set_code'] || row['set code'] || '';
    const rawFile = row['filename'] || row['file_name'] || row['file'] || row['filepath'] || row['image'] || row['img'] || '';
    const rawCondInput = row['condition'] || row['grade'] || 'Near Mint';
    const rawLangInput = row['language'] || row['lang'] || row['sprache'] || 'EN';
    const rawPrice = row['price'] || row['value'] || row['cardmarket_price'] || '';

    const rawCondition = normalizeCondition(rawCondInput);
    const rawLanguage = normalizeLanguage(rawLangInput);
    const rawLocation = 'DE'; // Always default seller country to DE (Germany)

    // Extracted candidate code if code is embedded in filename or zone ocr
    const extractedCode = extractCardCode(rawCode || rawFile || rawName);

    return {
      id: `scan_${Date.now()}_${index}`,
      index: index + 1,
      rawCode,
      rawName,
      rawSet,
      rawFile,
      rawCondition,
      rawLanguage,
      rawLocation,
      rawPrice: parseFloat(rawPrice) || null,
      detectedCode: extractedCode || rawCode || null,
      detectedName: rawName || null,
      status: extractedCode ? 'matched' : 'needs_review',
      cardDetails: null,
      marketPrices: null
    };
  });
}

/**
 * Pattern matcher for TCG Card Codes (One Piece, Pokémon, Yu-Gi-Oh, etc.)
 */
export function extractCardCode(text) {
  if (!text || typeof text !== 'string') return null;

  // One Piece TCG formats: OP01-001, ST01-001, EB01-001, P-001, PRB01-001
  const opMatch = text.match(/\b(OP\d{2}|ST\d{2}|EB\d{2}|PRB\d{2}|P)-\d{3}\b/i);
  if (opMatch) return opMatch[0].toUpperCase();

  // Pokémon TCG format: e.g. 123/197 or SV01-123
  const pokemonMatch = text.match(/\b(SV\d{2}|PAL|OBF|PAR|TEF|TWM|SFA|SCR)-\d{3}\b/i) || text.match(/\b\d{1,3}\/\d{1,3}\b/);
  if (pokemonMatch) return pokemonMatch[0].toUpperCase();

  // Yu-Gi-Oh format: LOB-001, SDK-001
  const yugiohMatch = text.match(/\b[A-Z0-9]{3,4}-[A-Z0-9]{3,4}\b/i);
  if (yugiohMatch) return yugiohMatch[0].toUpperCase();

  return null;
}
